// src/app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { OrganizationProvider } from "@/context/OrganizationContext";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { Toaster } from "@/lib/utils/toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CeleroPress Marketing Suite",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
    shortcut: '/icon.png',
    apple: '/icon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className={inter.className}>
        <QueryProvider>
          <AuthContextProvider>
            <OrganizationProvider>
              {children}
            </OrganizationProvider>
          </AuthContextProvider>
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}