// src/app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext"; // KORRIGIERT

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SKAMP Marketing Suite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className={inter.className}>
        <AuthContextProvider> {/* KORRIGIERT */}
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}